# Generated by Django 3.0.8 on 2020-07-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200703_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
